### ISSUE TITLE
The order of entries is based on alphabet instead of where they appear

### ISSUE THREAD

**Issue by aminya** [atom-ide-community/atom-ide-outline#38]
Using atom-typescript for this file:
https://github.com/atom-ide-community/atom-ide-outline/blob/master/src/providerRegistry.js

`removeProvider` comes after `getProvider`, which is not based on the file
![image](https://user-images.githubusercontent.com/16418197/87965795-f2b8a300-ca81-11ea-8c1e-76ced8927524.png)

**Comment by aminya** [comment]
@lierdakil Just checking, do you pass the outline content based on the alphabet?

**Comment by aminya** [comment]
I think this is specific to atom-typescript. This does not happen on ide-typescript.

**Comment by lierdakil** [comment]
This is consistent with how `atom-ide-ui` behaves.

Atom-TypeScript just passes items in whatever order tsserver returns those. I guess I could sort those by start position for consistency with builtin semantic view.

**Comment by aminya** [comment]
`ide-typescirpt` passes them based on the code appearance. It is better to see them based on the actual code. So if you do that it would be good. 

I will close this since it is not directly related to this package.
