### ISSUE TITLE
Icons not showing properly in outline for Python

### ISSUE THREAD

**Issue by Ron-SK** [atom-ide-community/atom-ide-outline#40]
I installed the atom-ide-outline package but I get question marks as icons for the outline. Screenshot is provided. 
<img width="584" alt="Screen Shot 2020-07-21 at 8 51 49 AM" src="https://user-images.githubusercontent.com/61721397/88057025-78def300-cb2f-11ea-93fb-96b568ba7663.png">

**Comment by Ron-SK** [comment]
Forgot to mention, this is Python

**Comment by aminya** [comment]
I am looking into this. In the last version, I changed some of the things in the package. I will check what has caused this.

**Comment by aminya** [comment]
Thanks for the report. This is solved in the new version @Ron-SK

**Comment by Ron-SK** [comment]
> I am looking into this. In the last version, I changed some of the things in the package. I will check what has caused this.

Thank you so much! Atom is my favorite text editor and I am so happy that there is still activity on it. Hopefully I can contribute to this in the future.

**Comment by aminya** [comment]
You're welcome! We would be happy to see your contributions and involvement. 🚀
