### ISSUE TITLE
Can't save edits when Outline is in operation

### ISSUE THREAD

**Issue by csturmer** [atom-ide-community/atom-ide-outline#50]
I am very new to Atom so I could be doing something wrong.  I installed the following Packages so I could have an Outline running for a Java project I am running.

atom-ide-outline
ide-java
atom-ide-ui

When I would edit a .java file, the small blue dot on the tab indicating the file needed to be saved would appear as it should.  However attempting to save the file would not remove the dot, nor would it physically save the file.  When I would attempt to close the tab I would be presented with two message boxes.  "'TaskStorageService.java' has changes, do you want to save them?" clicking the Save button would result in the second message box.  "'TaskStorageService.java' could not be saved. Error: undefined"

I tried Disabling the atom-ide-ui but that did not resolve the issue.  I then simply Disabled atom-ide-outline and ide-java and that fixed the problem.

BTW Thanks for creating this package.  It there is any more info or testing you need me to do, just drop me a note.

**Comment by aminya** [comment]
Could you try with the outline disabled but have the other two enabled? 

I am not sure if this is related to the outline package.

**Comment by csturmer** [comment]
aminya,

I installed the update for atom-ide-outline 1.8.0 (i think).

The next problem I had was "IDE-Java language server stopped unexpectedly.

Exit code 13"

So I am rebooting to see if that will fix that issue.  brb

**Comment by aminya** [comment]
The `IDE-Java language server stopped unexpectedly.` is because of ide-Java. You should open an issue there.
https://github.com/atom/ide-java

**Comment by aminya** [comment]
@csturmer Ok I found the reason. This is the fix for it. You should install the ide-java from this pull request:
https://github.com/atom/ide-java/pull/116

This is reported here: https://github.com/atom/ide-java/issues/115

**Comment by csturmer** [comment]
aminya,

you were right.  I disabled Outline and it must be isolated to either ide-java or atom-ide-ui.

wow! just saw your latest post.  let me go try that.  thank you!!!!

**Comment by csturmer** [comment]
Amin,

Thank you very much for helping with this.  It has been a great intro to parts of how the dev process is working here and how errors should be reported.  As a side note:  Below is what I used to fix the problem, on a Mac.
...
"ytx21cn commented on Feb 18

I don’t know if you got it working, but let me give you some more detailed steps. This assumes you are on a Linux OS. 1. ‘cd ~/.atom/packages/ide-java’ 2. Open ‘packages.json’ 3. Under the ‘dependencies’ key, find the line which says ‘atom-language client’ and up the version to ‘0.9.9’ 4. Run ‘npm install’ Now the Java IDE should use the newer dependency, and saving files should work again. I hope this helps. Matthias Varberg Ingesman"

**Comment by aminya** [comment]
You're welcome. I will get the maintainers to merge that pull request so you don't have to edit things manually. But that works for now. Enjoy coding in Atom!

**Comment by csturmer** [comment]
Hi Amin,

I am not sure where to file feature requests, so I thought I would run it past you.

I have a feature request for Outline.  It is a Setting that allows you to turn on or off sorting of groups of types.  What I mean by this is using a Java class as an example...

All the instance variables would be sorted by name.  All the methods would likewise be sorted by name, etc,

This makes using the Outline to look up by name quicker, especially if you have a lot of methods, etc. in a class.  Then you just (as now) select that item to jump to that point in the code.

Right now the default is each item in each sub-group is in the order they appear in the .java file.

EX:

class foo
{
   int var_1;
   int var_6;
   int var_3;

   private void method_6()  {;}
   private void method_1()  {;}
   private void method_2()  {;}
}


Tree now:
  ...
  i var_1
  i var_6
  i var_3
  m method_6
  m method_1
  m method_2
  ...

Proposed addition:
  ...
  i var_1
  i var_3
  i var_6
  m method_1
  m method_2
  m method_6
  ...

I started looking at the code for the outline and I am sure I could figure out how to make this change myself and contribute, but I figured I would run this by you.  I am sure you know exactly the best place to do the sort.  After looking at the code for Outline it might be when it is pulled from the editor but I have not had the time to look that deep in yet.

Anyway, I am loving using the Outline!

Thank you!
--Carl--

**Comment by aminya** [comment]
@csturmer Thanks for the request. I created an issue for it: https://github.com/atom-ide-community/atom-ide-outline/issues/51.

I was actually thinking about this. I will add this feature soon.

**Comment by aminya** [comment]
@csturmer This is added in the new version. Check it out!

**Comment by csturmer** [comment]
Hi Amin,

I love it so far!

Thank you!
--Carl--

**Comment by csturmer** [comment]
Hi Amin,

I see the new Setting in Outline but unchecking it does not cause the list to be re-sorted by name.  It still keeps it in the line number sorted arrangement.

Let me know if I missed something?

Thanks!
--Carl--
