### ISSUE TITLE
Disposable leaked in main.ts#addObservers

### ISSUE THREAD

**Issue by lierdakil** [atom-ide-community/atom-ide-outline#55]
https://github.com/atom-ide-community/atom-ide-outline/blob/d9609c7a4ed8d7790477ed087a92c6e38f808fa4/src/main.ts#L67-L72

A disposable is leaked here. As a concequence, onDidStopChanging events are never disposed of, and new ones are routinely created on changing editor focus. This might be the reason behind slowdowns @aminya observed in https://github.com/TypeStrong/atom-typescript/issues/1554

**Comment by aminya** [comment]
Oh sorry. Those big long names caused this issue 😄. I will fix it now.
