### ISSUE TITLE
the Outline doesn't work

### ISSUE THREAD

**Issue by aon24** [atom-ide-community/atom-ide-outline#64]
![atom](https://user-images.githubusercontent.com/22930355/91743930-51188b80-ebc1-11ea-9e53-85e287389e47.png)

**Comment by aminya** [comment]
Do you have atom-ide-javascript installed?

**Comment by aon24** [comment]
thank you, I installed atom-ide-javascript and everything works perfectly

**Comment by aminya** [comment]
You're welcome!
